import re

RESET_PATTERNS = [
    r"reset.{0,10}password",
    r"password.{0,10}reset",
    r"forgot.{0,10}password",
    r"forgot.{0,10}pass\b",
    r"change.{0,10}password",
    r"can.{0,5}t.{0,10}log.{0,5}in",
    r"unable.{0,10}log.{0,5}in",
    r"lost.{0,10}password",
    r"recover.{0,10}(account|password|access)",
    r"account.{0,10}locked",
    r"password.{0,10}expired",
    r"reset.{0,10}(password|kata\s+sandi|sandi|pw|pass)",
    r"(kata\s+sandi|sandi|pw|pass).{0,10}reset",
    r"lupa.{0,10}(password|kata\s+sandi|sandi|pw|pass|kata)",
    r"lupa.{0,10}(login|masuk|akun)",
    r"ubah.{0,10}(password|kata\s+sandi|sandi|pw|pass)",
    r"(tidak\s+bisa|gak\s+bisa|nggak\s+bisa|tidak\s+bisa).{0,15}(login|masuk|log\s+in)",
    r"(akun|account).{0,10}(terkunci|kunci|locked)",
    r"(password|sandi|kata\s+sandi|pk).{0,10}(kadaluarsa|expired|kedaluwarsa)",
    r"recover.{0,10}(akun|account|password|sandi)",
]
COMPILED_RESET_PATTERNS = [re.compile(p, re.IGNORECASE) for p in RESET_PATTERNS]

THANK_YOU_PATTERNS = [
    r"\bthank(s| you)\b",
    r"\bthanks?\s+for\b",
    r"\bterima\s+kasih\b",
    r"\bmakasih\b",
    r"\bappreciate(d|s)?\b",
]
COMPILED_THANK_YOU_PATTERNS = [re.compile(p, re.IGNORECASE) for p in THANK_YOU_PATTERNS]

REQUEST_INTENT_PATTERNS = [
    r"\bplease\b",
    r"\bkindly\b",
    r"\btolong\b",
    r"\bmohon\b",
    r"\bbantu(?:in)?\b",
    r"\bhelp\s+me\b",
    r"\bneed\s+help\b",
    r"\bneed\b",
    r"\bcan(?:'| )?t\b",
    r"\bcannot\b",
    r"\bunable\b",
    r"\blupa\b",
    r"\btidak\s+bisa\b",
    r"\bgak\s+bisa\b",
    r"\bnggak\s+bisa\b",
]
COMPILED_REQUEST_INTENT_PATTERNS = [re.compile(p, re.IGNORECASE) for p in REQUEST_INTENT_PATTERNS]

TECH_ISSUE_PATTERNS = [
    r"error\b",
    r"bug\b",
    r"crash\b",
    r"not\s+work|doesn'?t\s+work",
    r"broken\b",
    r"failed?\b",
    r"issue\b",
    r"problem\b",
    r"can't\s+access|cannot\s+access|unable\s+to\s+access",
    r"connection",
    r"timeout\b",
    r"500|404|502|503",
    r"slow\b",
    r"lag\b",
    r"freeze\b",
    r"unresponsive\b",
    r"hitam|blank\s+screen",
    r"login\s+failed|authentication\s+failed",
    r"putih\s+screen|white\s+screen",
    r"data\s+loss|lost\s+data",
    r"galat\b|kesalahan\b",
    r"bug\b|kutu\b",
    r"(error|crash).{0,10}(fatal|berat|parah)",
    r"(tidak\s+bisa|gak\s+bisa|nggak\s+bisa|tidak).{0,15}(bekerja|jalan|nge?run|work)",
    r"(tidak\s+bisa|gak\s+bisa|nggak\s+bisa|tidak).{0,15}(buka|akses|login|masuk|connect)",
    r"rusak\b",
    r"gagal\b|failed\b",
    r"(masalah|problem|kendala|gangguan|isu|issue)\b",
    r"lambat\b|lelet\b|slow\b",
    r"lag\b|putus\b|delay\b|putus\s+koneksi",
    r"(gak\s+|nggak\s+)?(bisa|bisa).{0,20}(akses|buka|login)\b",
    r"(tidak\s+|gak\s+|nggak\s+)?(bisa|jalan|bekerja)",
    r"eror\b",
    r"koneksi",
    r"timeout\b|time.{0,5}out",
    r"hang\b|hanging\b|freeze\b",
    r"(layar|screen).{0,10}(hitam|blank|putih|white|error|eror)",
]
COMPILED_TECH_PATTERNS = [re.compile(p, re.IGNORECASE) for p in TECH_ISSUE_PATTERNS]

UNSOLVED_PATTERNS = [
    r"still\s+(not|doesn'?t).{0,15}(work|working|fixed|resolved)",
    r"(still|still\s+have|still\s+getting).{0,10}(error|problem|issue|bug)",
    r"not\s+(yet\s+)?(fixed|resolved|solved)",
    r"(problem|issue).{0,10}(persists|remains|still\s+there)",
    r"hasn'?t.{0,10}(worked|fixed|resolved)",
    r"(trying|tried).{0,15}(but|still|yet).{0,10}(not|no|doesn'?t).{0,10}work",
    r"same.{0,10}(problem|issue|error)",
    r"still\s+broken\b",
    r"not.{0,10}working.{0,10}yet",
    r"(tidak|gak|nggak).{0,15}(bisa|bekerja|jalan)",
    r"(masih|tetap).{0,10}(error|eror|rusak|gagal)",
    r"(masalah|problema|issue).{0,10}(masih|tetap)\s+(ada|terjadi|berlangsung)",
    r"belum.{0,10}(selesai|diperbaiki|fixed|resolved)",
    r"(sudah|udah).{0,15}(coba|try).{0,10}(tapi|but|masih).{0,10}(tidak|gak|nggak)",
    r"sama.{0,10}(masalah|problema|error|eror)",
    r"masih\s+dapat\s+(error|eror|masalah)",
    r"(gak\s+|nggak\s+)?(bisa|bekerja|jalan)\s+(juga|juga\s+enggak)",
]
COMPILED_UNSOLVED_PATTERNS = [re.compile(p, re.IGNORECASE) for p in UNSOLVED_PATTERNS]

BLOCKED_SENDER_PATTERNS = [
    r"^no-?reply@",
    r"^noreply@",
    r"^notification@",
    r"^alert@",
    r"^support@google\.com$",
    r"@google\.com$",
    r"accounts-team@.*\.google\.com",
    r"@mail\.google\.com$",
    r"^mailer-daemon@",
    r"^postmaster@",
    r"^admin@",
    r"@outlook\.com$",
    r"@microsoft\.com$",
    r"@amazon\.com$",
    r"security-?alert@",
    r"verify.{0,20}@",
    r"no-?reply",
    r"please-do-not-reply",
]
COMPILED_BLOCKED_PATTERNS = [re.compile(p, re.IGNORECASE) for p in BLOCKED_SENDER_PATTERNS]
